#!/bin/bash
# 
# Generates the POSCAR of a dimer calculation
# Rodrigo García-Muelas
# July 18th, 2014. Tarragona.
# 
# Use with VASP 5.x or higher
# 
# INPUT
# $1 Path of the POSCAR file containing the coordinates
# $2 Path of the OUTCAR file containing the frequencies of the structure
# $3 <OUTPUT> POSCAR file
# $4 <OUTPUT> POSCAR file
# 
# Indexes
# a number of line
# b number of column
# c number of lattice vector, related to a
# d number of element, related to a
#
# VECTORS
# lattice
# element 
# numelem
# coordin
#

# PART 0 - SECURITY CHECKS

#if [ -e $3 ] ; then 
#echo "Warning! $3 already exist. Overwrite? (y/Y for yes)"
#read  overwrite
#case $overwrite in 
#y|Y|Yes|yes|YES) echo "$3 will be overwriten"          ;;
#*)               echo "No actions taken "     ; exit 1 ;;
#esac
#fi

#if [ -e $4 ] ; then
#echo "Warning! $4already exist. Overwrite? (y/Y for yes)"
#read  overwrite
#case $overwrite in
#y|Y|Yes|yes|YES) echo "$4 will be overwriten"          ;;
#*)               echo "No actions taken "     ; exit 1 ;;
#esac
#fi


IBRION=`grep IBRION $2 | awk '{print $3}'`
if [[ $IBRION -gt "8" || $IBRION -lt "5" ]] ; then 
echo "$2 is not an OUTCAR of a frequency job."
echo "No actions taken" ; exit 1 ; fi

# PART 1 - READ POSCAR 

a=0
totalelem=0
totalatom=0

while read linea ; do   ##### 1 #####
a=$(($a+1)) ; b=0 ; d=$(($a-9)) ; line[$a]=$linea ;
# echo $a; #echo $line;  if [ $a -lt 10 ] ; then  echo "${line[$a]}" ;  fi

for word in ${line[$a]} ; do   ##### 2 #####
b=$(($b+1))
#if [ $a -lt 10 ] ; then echo "previous to case a is $a" ; fi
case $a in
1) title=${line[$a]} ;;
2) scaling=$word ;;
[3-5])  c=$(($a-2)) ; lattice[$c$b]=$word ;; #; echo "coordinates $c $b $word ${lattice[$c$b]}" 
6) totalelem=$(($totalelem+1)) ; element[$b]=$word ;;
7) numelem[$b]=$word ; totalatom=$(($totalatom+$word))  ;;
8) selective=${line[$a]} ;;
9) directcartesian=${line[$a]} ;;
*) coord[$d$b]=$word ;; # echo "${coord[$d$b]}" ;;
esac
#if [ $a -lt 10 ] ; then echo "word value is $word" ; fi
done ##### 2 #####
done < "$1"  ##### 1 #####

sspec=`sed '6q;d' POSCAR`
~/bin/vasputil_direct2cartesian $1
mv $1.cart ccart
sed -i "6i $sspec" ccart

#echo $totalatom
~/bin/getdimer    $1 $2   pmt.pmt
tail -n $totalatom        pmt.pmt >> pmt.dim  
~/bin/posutil_sum ccart   pmt.dim $3 $4 0.150000000000000000000
rm -f pmt.???

